### ISSUE TITLE
PBI/Design tickets to look at

### ISSUE THREAD

**Issue by kbwagner** [USAJOBS-temp/openoppstasks#406]
- [ ] Events
- [ ] Student Marketplace
- [ ] Data Warehouse
- [ ] CMS
- [ ] Newsletter

**PBI Tickets to research:**
- [x] 60492 - endorsement idea Michelle presented
- [ ] 58649 - is this spike ready to be approved?  Not sure why it's on hold. Anything else that should be added?
- [ ] 58648 - is this something that should be flushed out more and put into a sprint?
- [ ] 41575 - Admin disapproval of opportunity.  This would be a good one to start mapping out.  If a community manager or sitewide goes to review/approve but they find something missing right now everything has to be done outside of the system.  This would be great to bring in.  We had an old design for this but suspect it's somewhat lost but allowed them to select a reason for disapproving and send notes.  I suspect we can talk through this without having a designer (we can try to do this for 13.2 possibly)
- [x] 56073 - Data warehouse - discuss what tickets we need for this.  Jordan/data team is aiming for October (13.5) but we can get all of this ready on our side.
- [ ] 56464 - newsletter - discuss what it would take to build this in Open Opps.  Is this feasible?  If so, start a ticket breakdown.
- [ ] 59780 - I had talked to Alex about this one briefly.  May need deanna's input.  How can we make next step more noticable if the applicant list is long.  Maybe have it at the top and bottom?  Or just the top?

**Comment by kbwagner** [comment]
@NObiako I looked through the backlog and pulled out a list of some you could discuss during PBI next week (won't get through them all I'm sure)

**Comment by NObiako** [comment]
@kbwagner  - We actually cancelled the PBI sessions this week. I was going to discuss a few on Thursday but we were missing some key team members.
