### ISSUE TITLE
KMS for Atlas

### ISSUE THREAD

**Issue by kbwagner** [USAJOBS-temp/openoppstasks#420]
Knowledge Management System:
- [x] Create file structure - Oct 1
- [x] Move over active files - Oct 8
- [x] Fill in spreadsheet - Oct 7
- [ ] Reference document - December

Miro: https://miro.com/app/board/o9J_l2gZzJA=/

**Comment by kbwagner** [comment]
@Bsdempsey @NObiako 

Here's what I can up with for the first round of Sharepoint/Teams mapping:  https://opm365.sharepoint.com/teams/USAJOBS/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fteams%2FUSAJOBS%2FShared%20Documents%2FAtlas&FolderCTID=0x0120001DB5A0BBB5C4284E8CB8DC9FE4CE24EB

- Communities - will house documents for all new communities so started a sub folder for Cyber for now
- Feature breakdown (Nnamdi created yesterday with student document)
- Help Content - where we can store draft help content we write to send to Debbie/Content
- Help Desk - Where quick descriptions or documents shared with the Macon Footprints team
- Release management - this one is a work in progress but what I see is a subfolder for every release with the completed UAT test script, deployment checklist, and draft release notes for every release
- Roadmapping - where roadmap documents will be stored
- Security Documents - where the latest version of the ATO, PIA, PTA will be stored
- Student Marketplace - I created a separate folder for this one but could also be a subfolder under Feature breakdown?
- System Reference documents - the email doc, the alert doc, eventually a permissions document, release planning document, etc.  

Is there anything else either of you can think of?  This can be a work in progress but have to set up a skeleton for strategic planning.  

Thanks!

**Comment by NObiako** [comment]
Maybe adding a folder for Sprint planning and Program status

Nnamdi Obiako
Business Analyst, Open Opportunities
U.S. Office of Personnel Management
***@***.******@***.***> | www.opm.gov/HRS<http://www.opm.gov/HRS>

[USAJOBS]<https://www.usajobs.gov/>

[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/USAJOBS> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/user/usajobsapp>
