### ISSUE TITLE
TFS templates

### ISSUE THREAD

**Issue by kbwagner** [USAJOBS-temp/openoppstasks#426]
- [x] Enhancement requests
- [x] Design/Content requests

**Comment by Bsdempsey** [comment]
Template for Design team created in TFS if and when we move in that direction.

**Comment by kbwagner** [comment]
@Bsdempsey can you create another template that we can use for the engagement team when they create an enhancement request in our backlog? 

Tags: Open Opps, Enhancements
Parent: Open Opps Enhancement requests (not sure if you can do that)

Things we need to know - can copy design template but also need to know who requested this (person, agency, community manager, etc.) and details about how often this issue is occurring.  Feel free to add any other fields you on @NObiako think would be helpful to capture.

**Comment by Bsdempsey** [comment]
@kbwagner - This is done. Enhancement template created.

**Comment by kbwagner** [comment]
@Bsdempsey thanks!  Closing...sent Slack message to engagement team and added how to document on Teams System Reference documents
