### ISSUE TITLE
13..8/13.9 Release notes

### ISSUE THREAD

**Issue by kbwagner** [USAJOBS-temp/openoppstasks#437]
13.8 and 13.9 will release together on 1/7/22

**Comment by Bsdempsey** [comment]
@kbwagner @NObiako  - Release notes for 13.8 and 13.9 have been submitted for review. 

(https://teams.microsoft.com/l/file/A5E9BAEC-F8AA-4FED-A7BE-1DC6B4DF97B3?tenantId=844ef997-7b63-48f0-882a-7dc8162e363b&fileType=docx&objectUrl=https%3A%2F%2Fopm365.sharepoint.com%2Fteams%2FUSAJOBS%2FShared%20Documents%2FAtlas%2FRelease%20management%2FRelease%20Notes%2FOpen%20Opps%20-%2013.8%20%26%2013.9%20Release%20notes.docx&baseUrl=https%3A%2F%2Fopm365.sharepoint.com%2Fteams%2FUSAJOBS&serviceName=teams&threadId=19:2f878e55283f4b9db73264bf18d7da13@thread.skype&groupId=4249ee37-a2b0-4885-87e2-a590586e15fa)

**Comment by kbwagner** [comment]
Thanks @Bsdempsey
